"use client";
import * as React from "react";
import { Menu } from "@base-ui/react/menu";
import { ChevronRight } from "lucide-react";
import { overlayLayers } from "./overlay-layers";
import { cn } from "./utils";

function DropdownMenu({ ...props }: React.ComponentProps<typeof Menu.Root>) { return <Menu.Root data-slot="dropdown-menu" {...props} />; }
function DropdownMenuGroup({ ...props }: React.ComponentProps<typeof Menu.Group>) { return <Menu.Group data-slot="dropdown-menu-group" {...props} />; }
function DropdownMenuSub({ ...props }: React.ComponentProps<typeof Menu.SubmenuRoot>) { return <Menu.SubmenuRoot data-slot="dropdown-menu-sub" {...props} />; }
function DropdownMenuSubTrigger({ className, children, ...props }: React.ComponentProps<typeof Menu.SubmenuTrigger>) { return <Menu.SubmenuTrigger data-slot="dropdown-menu-sub-trigger" className={cn("ds-type-menu-item focus:bg-surface-muted flex cursor-default select-none items-center gap-2 rounded-sm px-2 py-1.5 outline-hidden", className)} {...props}>{children}<ChevronRight className="ml-auto size-4 text-text-supporting" /></Menu.SubmenuTrigger>; }
function DropdownMenuSubContent({ className, ...props }: React.ComponentProps<typeof Menu.Popup>) { return <Menu.Portal><Menu.Positioner data-slot="dropdown-menu-sub-positioner" className={overlayLayers.popup}><Menu.Popup data-slot="dropdown-menu-sub-content" className={cn("min-w-56 overflow-hidden rounded-md border bg-surface-floating p-1 text-text-primary shadow-[var(--ds-shadow-floating)]", className)} {...props} /></Menu.Positioner></Menu.Portal>; }
function DropdownMenuTrigger({ ...props }: React.ComponentProps<typeof Menu.Trigger>) { return <Menu.Trigger data-slot="dropdown-menu-trigger" {...props} />; }
function DropdownMenuContent({ className, sideOffset = 4, side, align, ...props }: React.ComponentProps<typeof Menu.Popup> & { sideOffset?: number; side?: React.ComponentProps<typeof Menu.Positioner>["side"]; align?: React.ComponentProps<typeof Menu.Positioner>["align"] }) { return <Menu.Portal><Menu.Positioner data-slot="dropdown-menu-positioner" className={overlayLayers.popup} sideOffset={sideOffset} side={side} align={align}><Menu.Popup data-slot="dropdown-menu-content" className={cn("min-w-40 overflow-hidden rounded-md border bg-surface-floating p-1 text-text-primary shadow-[var(--ds-shadow-floating)]", className)} {...props} /></Menu.Positioner></Menu.Portal>; }
function DropdownMenuItem({ className, inset, variant = "default", ...props }: React.ComponentProps<typeof Menu.Item> & { inset?: boolean; variant?: "default" | "destructive" }) { return <Menu.Item data-slot="dropdown-menu-item" data-inset={inset} data-variant={variant} className={cn("ds-type-menu-item data-[variant=destructive]:text-danger-foreground data-highlighted:bg-surface-muted relative flex cursor-default select-none items-center gap-2 rounded-sm px-2 py-1.5 outline-hidden transition-colors data-disabled:pointer-events-none data-disabled:opacity-50 data-[inset=true]:pl-8", className)} {...props} />; }
function DropdownMenuLinkItem({ className, ...props }: React.ComponentProps<typeof Menu.LinkItem>) { return <Menu.LinkItem data-slot="dropdown-menu-link-item" className={cn("ds-type-menu-item data-highlighted:bg-surface-muted flex items-center rounded-sm px-2 py-1.5 outline-hidden", className)} {...props} />; }
function DropdownMenuLabel({ className, inset, ...props }: React.ComponentProps<"div"> & { inset?: boolean }) { return <div role="presentation" data-slot="dropdown-menu-label" data-inset={inset} className={cn("ds-type-menu-label px-2 py-1.5 font-medium data-[inset=true]:pl-8", className)} {...props} />; }
function DropdownMenuSeparator({ className, ...props }: React.ComponentProps<typeof Menu.Separator>) { return <Menu.Separator data-slot="dropdown-menu-separator" className={cn("-mx-1 my-1 h-px bg-border-default", className)} {...props} />; }
export { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuLinkItem, DropdownMenuSeparator, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger };
